<script>
    try{
        const num = 1;
        num.toUppCase();

        let val = val2 + 1;
    }catch( error ){
        if( error instanceof TypeError ){
            console.log( "TypeErrorが発生した時の処理" );
        }else if( error instanceof ReferenceError ){
            console.log( "ReferenceErrorが発生したときの処理" );
        }
    }
</script>